export enum WebhookEventEnum {
  CHARGE_CREATED = 'CHARGE_CREATED',
  CHARGE_COMPLETED = 'CHARGE_COMPLETED',
  CHARGE_EXPIRED = 'CHARGE_EXPIRED',
  TRANSACTION_RECEIVED = 'TRANSACTION_RECEIVED',
  TRANSACTION_REFUND_RECEIVED = 'TRANSACTION_REFUND_RECEIVED',
  MOVEMENT_CONFIRMED = 'MOVEMENT_CONFIRMED',
  MOVEMENT_FAILED = 'MOVEMENT_FAILED',
  MOVEMENT_REMOVED = 'MOVEMENT_REMOVED',
}
